version: '3.8'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - todolist_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pexample"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  app:
    build:
      context: .
      dockerfile: ./jenkins/Dockerfile
    ports:
      - "8080:8080"   # Frontend
      - "3000:3000"   # Backend
      - "8081:8081"   # Jenkins
    environment:
      - MYSQL_ROOT_PASSWORD=example
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./frontend:/app/frontend
      - ./backend:/app/backend
      - jenkins_data:/var/jenkins_home
    networks:
      - backend
      - frontend

volumes:
  todolist_data:
  jenkins_data:

networks:
  backend:
  frontend:
